import TimeTable from '../assets/scorepage/timetable.png';
export const mock_ranking = [
    {
        timetableId: 1,
        owner: '이대공돌이',
        score: 10,
        tableType: '나는한건물만판다',
        ranking: 1,
        tableImg: TimeTable,
        likeCount: 10,
        replyCount: 20,
    },
    {
        timetableId: 2,
        owner: '공대지박령',
        score: 20,
        tableType: '이화사랑산악회',
        ranking: 2,
        tableImg: TimeTable,
        likeCount: 3,
        replyCount: 6,
    },
    {
        timetableId: 3,
        owner: '나는감자',
        score: 30,
        tableType: '학교가밥먹여주냐',
        ranking: 3,
        tableImg: TimeTable,
        likeCount: 7,
        replyCount: 13,
    },
    {
        timetableId: 4,
        owner: '오전수업없다',
        score: 40,
        tableType: '상여자 특) 점심 먹고 등교함',
        ranking: 4,
        tableImg: TimeTable,
        likeCount: 37,
        replyCount: 24,
    },
    {
        timetableId: 5,
        owner: '달려라이화',
        score: 50,
        tableType: '쉬는시간에 치타가 되는 사람',
        ranking: 5,
        tableImg: TimeTable,
        likeCount: 43,
        replyCount: 12,
    },
    {
        timetableId: 6,
        owner: '밥묵자',
        score: 60,
        tableType: '점심은 포기 못해',
        ranking: 6,
        tableImg: TimeTable,
        likeCount: 3,
        replyCount: 2,
    },
    {
        timetableId: 7,
        owner: '행복한이대생',
        score: 70,
        tableType: '밥은 먹고 다니냐?',
        ranking: 7,
        tableImg: TimeTable,
        likeCount: 1,
        replyCount: 0,
    },
];
